--- #YAML:1.0
name:                Finance-Bank-US-INGDirect
version:             0.04
abstract:            Check balances and transactions for US INGDirect accounts
license:             perl
author:              
    - Steven N. Severinghaus <sns-perl@severinghaus.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Date::Parse:                   0
    HTML::Strip:                   0
    HTTP::Cookies:                 0
    LWP::UserAgent:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
