--- #YAML:1.0
name:                Finance-Bank-US-INGDirect
version:             0.02
abstract:            Check balances and transactions for US INGDirect accounts
license:             perl
author:              
    - Steven N. Severinghaus <sns-perl@severinghaus.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
